FROM debian:unstable AS download-tarballs

RUN apt-get update && \
    apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y \
    build-essential \
    python3 \
    black

RUN mkdir snek
COPY ./ snek/

WORKDIR ./snek
