.\"
.\" Copyright © 2019 Keith Packard <keithp@keithp.com>
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" General Public License for more details.
.\"
.TH SNEK-DUEMILANOVE-INSTALL 1 "snek-duemilanove-install" ""
.SH NAME
snek-duemilanove-instal \- Install Snek to Duemilanove
.SH SYNOPSIS
.B "snek-duemilanove-install" [OPTION]... [COMMAND]
.SH DESCRIPTION
.I snek-duemilanove-install
installs the Snek programming language on an ATmega328P Arduemilanove
Duemilanove board using the Optiboot boot loader.
.SH OPTIONS
.TP
\-hex <snek.hex>
Specifies the hex file to load to the board. The default is the
currently installed version of Snek.
.TP
\-port <port>
Specifies the serial port to use. The default is /dev/ttyUSB0.
.SH OPTIBOOT
Snek for the Duemilanove requires you to first install Optiboot on
your device.
You can use the Arduino IDE to install Optiboot on your
Duemilanove. Follow the instructions on the Optiboot web site:
https://github.com/Optiboot/optiboot to learn how to do that.
.SH AUTHOR
Keith Packard
