.\"
.\" Copyright © 2019 Keith Packard <keithp@keithp.com>
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" General Public License for more details.
.\"
.TH SNEK 1 "snek" ""
.SH NAME
snek \- Snek Programming Language
.SH SYNOPSIS
.B "snek" [--version|-v] [--help|-?] [--interactive|-i] [program.py]
.SH DESCRIPTION
.I snek
is a small Python-derivative suitable for embedded computers. This
host version is largely designed to help test the Snek system and
applications on larger machines
.SH COMMAND LINE OPTIONS
.TP
\--version or \-v
Reports the version number to stdout and then exits.
.TP
\--help or \-?
Prints usage information to stdout and then exits.
.TP
\--interactive or \-i
When a program is specified on the command line, enter interactive
mode after executing that program.
.SH USAGE
When a program is specified on the command line, snek runs it. Then,
if the --interactive flag is passed, it enters interactive
mode. Otherwise, it exits.
.P
When no program is specified on the command line, snek enters
interactive mode.
.SH AUTHOR
Keith Packard
